CREATE TABLE file_info (
  uuid uuid NOT NULL,
  name varchar(255) NOT NULL,
  id_type int2 NOT NULL,
  size int4 NOT NULL,
  last_change_time TIMESTAMP NOT NULL,
  upload_time TIMESTAMP NOT NULL,
  PRIMARY KEY (uuid)
);

CREATE TABLE types (
  id int2 generated BY DEFAULT AS IDENTITY,
  name VARCHAR(10) NOT NULL,
  PRIMARY KEY (id)
);

ALTER TABLE
  if EXISTS file_info
ADD
  CONSTRAINT file_type_fk FOREIGN KEY (id_type) REFERENCES types;

INSERT INTO types(name)
    VALUES ('png'), ('jpg'), ('gif'), ('bmp'), ('psd'), ('webp'), ('svg'),
           ('log'), ('txt'), ('doc'), ('docx'), ('html'), ('pdf'), ('json'), ('xml'),('xhtml'), ('css'),
           ('7z'), ('gz'), ('rar'), ('tar'), ('zip'),
           ('mp4'), ('avi'), ('mpg'), ('mov'),
           ('mp3'), ('m4a'), ('wav'),
           ('ppt'), ('pptx'), ('key'),
           ('xls'), ('xlsx'), ('xlsm'), ('xl');